### ISSUE TITLE
US02_HOME_infos

### ISSUE THREAD

**Issue by alyson-b69** [WildCodeSchool/Lyon-js-202005-project-gamovore#2]
En tant que visiteur
Je veux me renseigner sur le site et ses conditions
Afin de voir son utilité, savoir si c'est gratuit
[Users Stories Tab](https://docs.google.com/spreadsheets/d/1GnZImQ_P9jnDa__WM6hQtP8kWjVeJSygyL7bxtxWcaU/edit#gid=1469205909)

**Comment by alyson-b69** [comment]
1st task : About us section
2nd task : tutorial section

**Comment by Seblecaribou** [comment]
The US02 is no longer in the pipeline.
