### ISSUE TITLE
#2 Create tutorial section

### ISSUE THREAD

**Issue by alyson-b69** [WildCodeSchool/Lyon-js-202005-project-gamovore#20]
Create tutorial section (How to Login, What's profil view, what's gamelist view, what's gamovores view

**Comment by alyson-b69** [comment]
Attention ! D'après le client, cette section n'est pas prioritaire!

**Comment by Seblecaribou** [comment]
The client doesn't want a tutorial section. The US02 is no longer in the pipeline.
