### ISSUE TITLE
US04_HOME_SignupForm

### ISSUE THREAD

**Issue by alyson-b69** [WildCodeSchool/Lyon-js-202005-project-gamovore#4]
En tant que visiteur
Je veux renseigner mes données
Afin de m'inscrire

[Users Stories Tab](https://docs.google.com/spreadsheets/d/1GnZImQ_P9jnDa__WM6hQtP8kWjVeJSygyL7bxtxWcaU/edit#gid=1469205909)

**Comment by P-P-P-Pablo** [comment]
doublon avec la precedente

**Comment by P-P-P-Pablo** [comment]
done and closed
