### ISSUE TITLE
#19 create game Page component

### ISSUE THREAD

**Issue by P-P-P-Pablo** [WildCodeSchool/Lyon-js-202005-project-gamovore#49]
formating data from API to react component
+ "add to collection button"

this is just for the cards in the game list we need another component for game profile.

info in this card:
name
jaquette
platform
coop/compet
nbr of gamovores playing this game (added to collection/interest ?)

**Comment by alyson-b69** [comment]
the gamovores are in other components ! Add to my collection is on the game Details. Sorry for the branch (same that gameList)

**Comment by P-P-P-Pablo** [comment]
done and closed
