### ISSUE TITLE
#10 navigation menu

### ISSUE THREAD

**Issue by Seblecaribou** [WildCodeSchool/Lyon-js-202005-project-gamovore#80]
Create a menu that will display a component four times:
My Profile, My Games, My CoGamovores, My Messages
AND
display a logout component

 ![Screenshot from 2020-07-29 16-35-02.png](https://images.zenhubusercontent.com/5f170bc17f0e2e51d3e1cda1/fd0e4652-e75b-4f5c-9a6d-3886733b7724)

**Comment by P-P-P-Pablo** [comment]
le fameux menu déroulant
