### ISSUE TITLE
Naming convention should confuse beetween ul and Ul

### ISSUE THREAD

**Issue by bugsfunny** [WildCodeSchool/Lyon-js-202005-project-gamovore#81]
https://github.com/WildCodeSchool/Lyon-js-202005-project-gamovore/blob/2c64a60be600c4fb7751ff32171ca7cdecd6861a/src/components/Ul.js#L3

**Comment by EthernalSlayer** [comment]
yes maybe you're welcom for better idea. It's just a convention in our group

**Comment by alyson-b69** [comment]
Yes Guillaume, I have a "piste" ;) I will change that tomorrow (i have to go now)

**Comment by alyson-b69** [comment]
I have change that in new PR (not yet reviewed ) ;)
