### ISSUE TITLE
Why boxbox is outside of component ?

### ISSUE THREAD

**Issue by bugsfunny** [WildCodeSchool/Lyon-js-202005-project-gamovore#82]
and what is boxbox... (naming)

**Comment by EthernalSlayer** [comment]
boxbox is the name for component that contain others components. And why is he outside ? it's just a group convention. No technical reason especially

**Comment by alyson-b69** [comment]
boxbox is our private joke ;) box in the box. We think we will modified that later, but now, it's just for us, have a vision of boxes.

**Comment by bugsfunny** [comment]
ok think about i will not  accept PR with this ;-)

**Comment by alyson-b69** [comment]
good for us, removing ok ;)
