### ISSUE TITLE
commit empty file is not a good idea...

### ISSUE THREAD

**Issue by bugsfunny** [WildCodeSchool/Lyon-js-202005-project-gamovore#84]
src/containers/NavBar.js

Lot of code seem useless...

**Comment by EthernalSlayer** [comment]
the empty file have been created for create folders because an empty folder cannot be add in git.

**Comment by bugsfunny** [comment]
commit an empty folder is not a good idea too !!

**Comment by alyson-b69** [comment]
We just wanted to be too much organized ;)

**Comment by alyson-b69** [comment]
Delete ok :)
