### ISSUE TITLE
is sign up in priorities ?

### ISSUE THREAD

**Issue by bugsfunny** [WildCodeSchool/Lyon-js-202005-project-gamovore#87]
https://github.com/WildCodeSchool/Lyon-js-202005-project-gamovore/blob/a56931a5deee58e8e022449e6aa2d60acdd3ce67/src/components/SignUpForm.js#L3

**Comment by alyson-b69** [comment]
Oops p3... I don't know why we make them in the sprint backlog :/

**Comment by alyson-b69** [comment]
We reorganize US for not doing this mistake another time.
