### ISSUE TITLE
Are you sure about put all component in router ?

### ISSUE THREAD

**Issue by bugsfunny** [WildCodeSchool/Lyon-js-202005-project-gamovore#88]
https://github.com/WildCodeSchool/Lyon-js-202005-project-gamovore/blob/a56931a5deee58e8e022449e6aa2d60acdd3ce67/src/containers/Sidebar.js#L10

**Comment by alyson-b69** [comment]
Not really ...

**Comment by alyson-b69** [comment]
Deleted for the moment.
