### ISSUE TITLE
Were is the switch ? are you sure to make a functional PR with your process ?

### ISSUE THREAD

**Issue by bugsfunny** [WildCodeSchool/Lyon-js-202005-project-gamovore#89]
https://github.com/WildCodeSchool/Lyon-js-202005-project-gamovore/blob/a56931a5deee58e8e022449e6aa2d60acdd3ce67/src/containers/Sidebar.js#L13

**Comment by alyson-b69** [comment]
no it's didn't functionnal, it's to don't forbidden them...

**Comment by EthernalSlayer** [comment]
for now we have only one page

**Comment by bugsfunny** [comment]
so you do not need router, please keep your code consistent !!!

**Comment by alyson-b69** [comment]
router deleted ;)
