### ISSUE TITLE
#37 Create fake users + authentification

### ISSUE THREAD

**Issue by Seblecaribou** [WildCodeSchool/Lyon-js-202005-project-gamovore#97]
Create a database of a couple of fake users. 

This fake DB should take the form of an array of objects. Each object should have the following properties:
-Pseudo
-Mail
-Password
-Departement
-Description
-Availibilities
-Favorite Game Modes
-Favorite Genres
-IDs of the favorite games
-IDs of the favorite Gamovores

**Comment by P-P-P-Pablo** [comment]
create authentification system at the same time :
-display form on click
-create connection function (with condition pseudoTapé==pseudoBDD)

**Comment by P-P-P-Pablo** [comment]
done and closed
